### ISSUE TITLE
multiple activity  declared in src/main/java  cause crash

### ISSUE THREAD

**Issue by YouriZhang** [nailperry-zd/LazierTracker#10]
![image](https://user-images.githubusercontent.com/23033652/34726095-fc8225da-f58d-11e7-8636-0a2a1d14a1cd.png)

**Comment by YouriZhang** [comment]
if single activity declared  it works，but multiple activity declared cause crash，how can I resolve this issue？

**Comment by nailperry-zd** [comment]
@YouriZhang What do you mean by "multiple activity declared in src/main/java"? Please add your Activity in your  AndroidManifest.xml. When you want to make a new activity, you should register it in your AndroidManifest.xml.

**Comment by snowaves** [comment]
No！It isn't because you haven't register that activity in your ‘AndroidManifest.xml’，you should comment out that  injection in your gradle.I think this reason is because there issome exception in your activity,comment out the injection in gradle ,you will find your exception in activity.
